# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/javascript"
    schedule:
      interval: "daily"
