name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        java-version: [ 8, 11 ]

    name: Java ${{ matrix.java-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x86 # (x64 or x86) - defaults to x64
    - name: sonar-secrets-java
      shell: bash {0}
      run: |
        make build-java-jar
    - name: sonar-secrets-javascript
      run: |
        make build-javascript-jar
